tests/fv3_conf/ccpp_gsd_run.IN: add logic to use correct field table, depending on choice of microphysics schemes and whether a TKE PBL scheme is used

diff --git a/tests/fv3_conf/ccpp_gsd_run.IN b/tests/fv3_conf/ccpp_gsd_run.IN
--- a/tests/fv3_conf/ccpp_gsd_run.IN
+++ b/tests/fv3_conf/ccpp_gsd_run.IN
@@ -25,14 +25,23 @@ elif [ $LSM = 3 ]; then
   cp  @[RTPWD]/FV3_input_data_gsd/diag_table_gsd_ruc  diag_table
 fi
 
-# Copy field table - just try if this works
-#if [ $IMP_PHYSICS = 8 && $DO_MYNNEDMF = .T. ]; then
-#  cp    @[RTPWD]/FV3_input_data_gsd/field_table_gsd field_table
-#elif [ $IMP_PHYSICS = 8 ]; then
-#  cp    @[RTPWD]/FV3_input_data_gsd/field_table_thompson field_table
-#...
-#fi
-cp    @[RTPWD]/FV3_input_data_gsd/field_table_gsd field_table
+# Copy field table, depending on microphysics choice and whether MYNN/SATMEDMF is used
+if [ $IMP_PHYSICS = 8 ]; then
+  if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+    cp  @[RTPWD]/FV3_input_data_gsd/field_table_gsd field_table
+  else
+    cp  @[RTPWD]/FV3_input_data_gsd/field_table_gf_thompson field_table
+  fi
+elif [ $IMP_PHYSICS = 11 ]; then
+  if [ $DO_MYNNEDMF = .T. ] || [ $SATMEDMF = .T. ]; then
+    cp @[RTPWD]/FV3_input_data_gsd/field_table_suite2 field_table
+  else
+    cp @[RTPWD]/FV3_input_data/field_table_gfdlmp field_table
+  fi
+else
+  echo "ERROR, no field table configured for IMP_PHYSICS=${IMP_PHYSICS}"
+  exit 1
+fi
 cp    @[RTPWD]/FV3_input_data/*configure .
 
 # Thompson MP lookup tables - copy standard and SIONlib tables of precomputed tables
